### ISSUE TITLE
error on configuring...

### ISSUE THREAD

**Issue by llnlln** [jjhenkel/code-vectors-artifact#1] opened 2019-02-26 10:43 UTC
The following error occurred when I ran the command `make end-to-end-redis`,
![screenshot from 2019-02-26 18-32-37](https://user-images.githubusercontent.com/32690972/53407013-265edd00-39f6-11e9-9953-0c7b358fa530.png)

I have installed gcc and g++(5.4.0), but I still reported this error. Can you provide some suggestions?

**Comment by jjhenkel** [comment] 2019-02-27 18:56
Hi @llnlln,

Could you provide a little bit more output? (Or a text file of the whole output of the command.)

Thanks!

**Comment by llnlln** [comment] 2019-02-28 02:20
Hi@jjhenkel,

The following output.txt file shows the output of the command `make end-to-end-redis`.

Thanks!

[output.txt](https://github.com/jjhenkel/code-vectors-artifact/files/2913121/output.txt)

**Comment by jjhenkel** [comment] 2019-02-28 02:52
Hi @llnlln ,

Can you try running the following (in the root of the repository):

```bash
git checkout arbitrary-repos
git pull
make end-to-end-redis
```

I was able to reproduce your issues locally---looks like I messed something up on master when I was helping someone else out with examples of ingesting other C repositories. The easy fix is to use the `arbitrary-repos` branch. I'll be sure to fix up `master` soon---just might not get to it for a few days.

Thanks!

**Comment by llnlln** [comment] 2019-02-28 04:46
Hi@jjhenkel,

I have run the following command 

```
git checkout arbitrary-repos
git pull
make end-to-end-redis
```

the result is as follows. 

![result](https://user-images.githubusercontent.com/32690972/53541395-908d9400-3b54-11e9-8914-e579dccef98f.png)

Thanks!

**Comment by jjhenkel** [comment] 2019-02-28 04:59
Great! I'll close this issue then; feel free to reopen/open another issue if you run into anything else.

**Closed as completed by jjhenkel** 2019-02-28 04:59 UTC
